CREATE TABLE IF NOT EXISTS telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    sensor_type VARCHAR(100) NOT NULL,
    reading_type VARCHAR(20) NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_telemetry_device_time
ON telemetry (device_id, event_time DESC);
